# Generated by Django 3.0.7 on 2021-12-17 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='No Title', max_length=264)),
                ('thumbnail_url', models.URLField(unique=True)),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='No Description', max_length=500, null=True)),
            ],
        ),
    ]
