# Generated by Django 3.0.7 on 2021-12-17 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0002_remove_video_publishing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publishing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
