# Generated by Django 3.0.7 on 2021-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0003_video_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, default='No Description', max_length=500, null=True),
        ),
    ]
